### ISSUE TITLE
Implement prebuilt macros allowlists

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#1769]
## Summary

Due to security concerns (binary builds are a great hacking vector), loading AOT compiled binaries should be off-by-default.
As a configuration mechanism, employ a whitelisting mechanism that users can put in `Scarb.toml`:

```toml
[package]
name = "hello"
version = "1.0.0"

[dependencies]
some_macro = "0.1"

[tool.scarb]
allow-prebuilt-macros = [
    "some_macro"
]
```

Matching will happen on `PackageName`.  Matching applies to the entire dependency subtree, that is, if package `x` is using macro `y` as its dependency, a whitelist entry `x` will allow package `y`. This means that a single whitelist item will enable all instances of a given macro, regardless of version/source differences. The transitive nature of the list also makes preserving some context within `Scarb.toml` file.

## Example: usage by Starknet Foundry

Change `snforge init` template to emit a following `Scarb.toml` file for new projects:

```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2023_11"

# ...

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }
assert_macros = "2.8.4"

# ...

[tool.scarb]
allow-prebuilt-macros = [
    "snforge_std"
]

# ...
```

> [!NOTE]
> No such task was created in Foundry repo.
