### ISSUE TITLE
language server is being poluted by scarb

### ISSUE THREAD

**Issue by tdelabro** [software-mansion/scarb#1906]
I use helix as text editor, with cairo language server.

here is my scarb.toml
```toml
[package]
name = "invoice_payment"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.2"
openzeppelin_token = "0.20.0"
openzeppelin_presets = "0.20.0"
openzeppelin_utils = "0.20.0"

[dev-dependencies]
snforge_std = "0.35.1"
assert_macros = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["openzeppelin_presets::erc20::ERC20Upgradeable"]

[scripts]
test = "snforge test"

# Visit https://foundry-rs.github.io/starknet-foundry/appendix/scarb-toml.html for more information

# [tool.snforge]                                             # Define `snforge` tool section
# exit_first = true                                          # Stop tests execution immediately upon the first failure
# fuzzer_runs = 1234                                         # Number of runs of the random fuzzer
# fuzzer_seed = 1111                                         # Seed for the random fuzzer

# [[tool.snforge.fork]]                                      # Used for fork testing
# name = "SOME_NAME"                                         # Fork name
# url = "http://your.rpc.url"                                # Url of the RPC provider
# block_id.tag = "latest"                                    # Block to fork from (block tag)

# [[tool.snforge.fork]]
# name = "SOME_SECOND_NAME"
# url = "http://your.second.rpc.url"                         
# block_id.number = "123"                                    # Block to fork from (block number)

# [[tool.snforge.fork]]
# name = "SOME_THIRD_NAME"
# url = "http://your.third.rpc.url"
# block_id.hash = "0x123"                                    # Block to fork from (block hash)

[profile.dev.cairo]                                        # Configure Cairo compiler
unstable-add-statements-code-locations-debug-info = true   # Should be used if you want to use coverage
unstable-add-statements-functions-debug-info = true        # Should be used if you want to use coverage/profiler
inlining-strategy = "avoid"                                # Should be used if you want to use coverage

# [features]                                                 # Used for conditional compilation
# enable_for_tests = []                                      # Feature name and list of other features that should be enabled with it
```

And here is my "list all errors" pannel in helix. Most of them comes from files with path like ` ~/Library/Caches/com.swmansion.scarb/registry/src/scarbs.xyz-9djtpev4jug5q/openzeppelin_token-0.20.0/`

<img width="1583" alt="Image" src="https://github.com/user-attachments/assets/31492bd2-616d-4f5b-8d8b-ca2ee928e616" />

My scarb project does compile btw.

Can you make those go away?
