### ISSUE TITLE
Pulling prerelease dependencies yields package not found error

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#600]
### Problem

Looking for prerelease packages (`X.Y.Z-P`) as dependencies with unspecified `version`, triggers _package not found_ error. This is caused by the fact that we assume `*` as default version requirement, which actually does not match any prereleases.

### Steps

Assuming following package:

```toml
[package]
name = "foo"
version = "0.7.0-rc.0"
```

If we try to declare a following dependency pointing to it:

```toml
[dependencies]
foo = { path = "path to foo" }
```

We'll get a following error:

```
error: cannot find package foo
```

But the following works:

```toml
[dependencies]
foo = { version = ">=0.7.0-rc.0", path = "path to foo" }
```

### Notes

Hotfix is being worked on right now.

### Version

```text
0.6.2
```
