### ISSUE TITLE
Refine `allowed-libfuncs` fields syntax

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#623]
### Problem

The current syntax of [`allowed-libfuncs-*` fields](https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#allowed-libfuncs-validation) is clunky, though it was the easiest to implement.

### Proposed Solution

Make the following possible, and establish a new convention for this field:

```toml
# Enable validation with Scarb defaults, this is the default current behaviour.
allowed-libfuncs = true

# Disable validation entirely.
allowed-libfuncs = false

# Formerly: allowed-libfuncs-list.name = "NAME"
allowed-libfuncs = "NAME"
allowed-libfuncs = { name = "NAME" }

# Formerly: allowed-libfuncs-list.path = "NAME"
allowed-libfuncs = { path = "PATH" }

# Formerly: allowed-libfuncs-deny = T/F
allowed-libfuncs = { deny = true }
allowed-libfuncs = { deny = false }

# Mixing, for example.
allowed-libfuncs = { deny = false, path = "PATH" }
```

> [!IMPORTANT]
> Additionally, deprecate the old way, both in Scarb docs and emit warnings in code to the user, with hints how it should look like now. We need to maintain compatibility for at least 6 months, like Starknet does.

### Notes

The recently released https://github.com/dtolnay/serde-untagged crate allows quite pleasant implementation of this.

The entire code for this logic starts here: https://github.com/software-mansion/scarb/blob/6052df85ca5148dab0296815a3e84bcca728569e/scarb/src/compiler/compilers/starknet_contract.rs#L41-L43
