### ISSUE TITLE
Add `lib.sierra-text` property to generate textual Sierra representation of package's code

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#634]
Add the following property to Scarb.toml

```toml
[lib]
sierra-text = true
```

Defaults to `false`.

Enabling it will generate the "original" `*.sierra` artefact.
