### ISSUE TITLE
Add `publish` field to Scarb.toml to mark package as not publishable to the registry

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#636]
Following, package should yield errors when doing `scarb package` and `scarb publish`.

```toml
[package]
name = "foobar"
version = "1.0.0"
publish = false
```

This field should be `true` by default.
